### ISSUE TITLE
main project and plugin project have the same jar problem

### ISSUE THREAD

**Issue by 408599764** [decebals/pf4j#119]
main project and plugin project have the same jar  for example they all have org.springframework.spring-beans jar will throws Exception
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of ro/fortsoft/pf4j/PluginClassLoader) previously initiated loading for a different type with name "org/springframework/beans/factory/BeanFactory"
I don't want to insert <scope>provided</scope> for maven dependency because the plugin doesn't know which jar is the main project dependency.the other same jar will throws Exception too.please help me to solve it.

**Comment by decebals** [comment]
What I understand from your comment:
- you have a `Spring` application (Spring framework in classpath)
- you have a plugin that also use `Spring` (Spring framework in classpath)
In this situation, if you use Maven, you should have Spring declared as dependency in the `pom.xml` of application and also you should have Spring declared as dependency in the `pom.xml`of plugin but with scope __provided__.

The idea is to not have the same jar (as dependency) in application classpath and the plugin classpath because the same class loaded with two different class loaders is finally two different classes.

I don't understand your affirmation:
> I don't want to insert provided for maven dependency because the plugin doesn't know which jar is the main project dependency.the other same jar will throws Exception too

**Comment by 408599764** [comment]
I want they can have same jar because I will put the plugin to the other people write and I don't want to tell every one what jar i have dependency, even though they not have same jar but my application will insert new function may be must dependency the jar which was include by plugin.

**Comment by decebals** [comment]
> I want they can have same jar

Do you want the same artifact version for each project/plugin?

You know that each plugin must have a dependency to spring framework, so for each project you:
```
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-core</artifactId>
    <version>4.3.5.RELEASE</version>
    <scope>provided</provided>
</dependency>
```

in `pom.xml` file.
If you have a structure like I used in my projects:
```
my-projects
   - app
   - plugins     
      - plugin1
      - plugin2
```

you can push the above line (dependency to spring) in `pom.xml` from `plugins` folder, in this mode each plugin inherit the dependency from parent and you are not force to add dependency in each plugin project.

**Comment by 408599764** [comment]
my projects is that structure too.thats solve is not perfect.if plugin can't dependency any jar,the plugin can't for the everyone use, its just for the app developer. other people use plugin have some limit.
anyway that way it can solve problem, tell the other don't dependency some jar which already dependency.
the last, thank you for your help.
