### ISSUE TITLE
Simplify main README

### ISSUE THREAD

**Issue by janhoy** [decebals/pf4j#166]
It is growing huge, it should just be a simple description and getting started. 

We can then put the complete formal documentation somewhere else (GitHub Wiki or https://readthedocs.org/)

**Comment by decebals** [comment]
You have write. I disused this aspect but I don't know if the discussion was the context of PF4J or Pippo. To many projects :)
For [Pippo](http://www.pippo.ro/) I use gh-pages and a separate git(hub) repository https://github.com/decebals/pippo-site.

We can start with GitHub Wiki because is a simple solution. If you have other idea please let me know. I am open to other solutions.

**Comment by janhoy** [comment]
GH-pages looks fine. And pf4j.org is available :-) And we even have a logo, hehe.

**Comment by decebals** [comment]
With gh-pages we have full control. The missing feature from Pippo site is that you cannot search in pages.

**Comment by decebals** [comment]
See http://www.pf4j.org (the source is available on https://github.com/decebals/pf4j-site).
