### ISSUE TITLE
Specific methods in different plugins

### ISSUE THREAD

**Issue by lucasbuschlinger** [decebals/pf4j#187]
Hi decebals,

I have the following problem:
We have a base structure for a kind of plugin.
In their respective implementations I want them to have specific methods, imagine setThis(args) in Plugin A and setThat(args) in Plugin B.
These methods are not declared within the Interface resembling the ExtentionPoint.
Now the problem is, that I can not access these specific methods when loading these plugin.

How can I achieve this, or is this not possible?

Greetings and thanks in advance,
Lucas

**Comment by decebals** [comment]
It's very clear for me what you try to achieve. An `ExtensionPoint` should be an interface or an abstract class.
You can do the plugin a singleton, in this mode you can call a method of plugin from another plugin.
Other variant, without singleton, is to use `pluginWrapper.getPluginManager().getPlugin(id)`.
See if https://github.com/decebals/pf4j/issues/181#issuecomment-347946858 helps you.

**Comment by lucasbuschlinger** [comment]
Thank you very much for the quick answer, I will look into it.
If I encounter any further problems I'll get back to you, but this might take a few days.

**Comment by lucasbuschlinger** [comment]
I've looked into it and I think I did not quite get across what I meant. I will try to elaborate further and with more detail:

We have a system for which we are implementing plugins for exporting data into different formats (CSV, Json and so on).

In the interface extending ExtensionPoint we have defined some basic functionality shared by all export plugins, such as writing to a file or loading configuration.
What I now want to do is to have a setter for different types of objects in different implementations of the plugins. So for example in plugin A I want to set List<Type> and in plugin B I want to set a DatabaseObject. So the methods could be setList(...) and setDatabase(...). But if I now go ahead and declare these methods in the classes implementing the interface (and marked with @Extension) they are not accessbile when using the plugin (as far as I see only those declared in the interface are).

I currently see two solutions:
- Have all these specific methods declared inside the interface but only really implement them in the corresponding plugin implementation and leave them empty in others
- Have a very generic method like setObject(Object obj) and then implementing this in the plugins.If I remember correctly this would have me casting (would like to avoid this) to List or DatabaseObject and a not very clear name (worse usability)

Is there any way to do this nicer? What I have in mind is:

interface X extends ExtensionPoint{
  methodA(...);
  methodB(...);
}

PluginA extends Plugin {
  constructorMatchingSuper();

  pluginAImplementation implements X{
    methodA(...){...}
    methodB(...){...}
    specificMethodA(...){...}
  }
}

PluginB extends Plugin {
  constructorMatchingSuper();

  pluginBImplementation implements X{
    methodA(...){...}
    methodB(...){...}
    specificMethodB(...){...}
  }
}

And thus having access to methodA, methodB and specificMethodA when using an instance of PluginA and methodA, methodB and specificMethodB when using an instance of PluginB.

I hope that I now managed to bring my point and problem clearer across to you.

Thank you in advance!

**Comment by lucasbuschlinger** [comment]
It seems like I can access the specific methods by Casting the Plugins from an general Exporter to a specific exporter.

It would then look like the following:

Original:
PluginManager manager = new DefaultPluginManager(Paths.get("export"));
manager.loadPlugins();
manager.startPlugin("ExporterA");
Exporter exp = manager.getExtensions(Exporter.class).get(0);

Now:
PluginManager manager = new DefaultPluginManager(Paths.get("export"));
manager.loadPlugins();
manager.startPlugin("ExporterA");
ExporterA.ExporterAImplementation exp = (ExporterA.ExporterAImplementation) manager.getExtensions(Exporter.class).get(0);

This still is not very pretty but the reason is, that the specificMethodA() is simply unknown to the interface Exporter.

**Comment by decebals** [comment]
If I understand correctly you want a mechanism for plugin (or extension)  configuration. You want to inject some dependencies (like connection to database) in your plugin (or extension) from your core application, after you load and start the plugins. Is it correct?

**Comment by lucasbuschlinger** [comment]
Yes that's about it.

I have now solved it by adding the generic setAdditional(Object object) method to my interface and then having private methods like setDatabase(..) in the plugin implementation which are then used by setAdditional (of course with proper type checking).

**Comment by decebals** [comment]
Maybe a good move is to change the issue title with something more appropriate (something like "how to configure the plugins"). Maybe other people can come with solutions if the problem domain is clear and general.

Personally, I will try to use a custom implementations for `PluginManager` and `Plugin`, something like `AcmePluginManager` (extends DefaultPluginManager) and `AcmePlugin` (extends Plugin).
The `AcmePluginManager` can contain new helper method like `getSetings(): Properties` (or Map) or, more directly a `getDatabaseConnection(): Connection` method.
I will use pool technique instead of push (I will extract the database connection in AcmePlugin from AcmePluginManager and not viceversa, push database connection from AcmePluginManager to AcmePlugin).
If I want something more generic, probably I will use the approach used by me in other personal project, [Pippo](https://github.com/decebals/pippo). In Pippo we have a `application.properties` file that keeps the all application properties, and a PippoSettings class that allow us to read very easy the value for different properties (as Integer, String, Double, Date, List, ...).
I use an easy property name convention to group properties in application.properties (a property prefix). So, you can use the pluginId as prefix, something like:
plugin_1.jdbc.url=
plugin_1.jdbc.username=
plugin_1.jdbc.password=
plugin_2.propA=
plugin_2.propB=

In AcmePlugin, I will add a new method getSettings (or getConfig) method that will return all the propeties of plugin for application.properties, of course without ("plugin1." prefix) like jdbc.url, jdbc.username, jdbc.password.

Make sense for you?

**Comment by lucasbuschlinger** [comment]
Hey sorry for the late answer.

We currently solved it by using a generic method as described above.
We might look further into this later.

Thank you for your assistance!
