### ISSUE TITLE
Missing dependency in Maven Central

### ISSUE THREAD

**Issue by najiji** [decebals/pf4j#86]
### Problem
Using pf4j causes `Failed to load class "org.slf4j.impl.StaticLoggerBinder"` Error

### Cause
The POM file in Maven Central is missing the `slf4j-simple` dependency

### Workaround
Manually include `slf4j-simple` version 1.7.5 into your project.

**Comment by decebals** [comment]
Can you tell me what PF4J version you use?

**Comment by najiji** [comment]
Yes, I'm using 0.11.0, which seems to be the newest one available on mvn central

**Comment by decebals** [comment]
The idea is that PF4J use only `slf4j-api` to produce (log) events. In your application you must use a `slf4j` concret implementation. You can choose from slf4j-simple, slf4j-log4j, logback. java.util.logging, ... (see http://www.slf4j.org/ for a full list). In my opinion your issue is not a bug because you must choose a concrete implementation of slf4j in your application. I cannot add `slf4j-simple` as dependency because in my projects I use `slf4j-log4j` and someone maybe works with `slf4j-logback`.
Make sense for you?

**Comment by najiji** [comment]
Yes, this makes perfect sense. However, there may occur problems with different versions.
Currently, you use version 1.7.5 of slf4j-api.

So, as soon you update that version in pf4j, users (that change to newer versions of pf4j) need to update their version of slf4j implementation as well (if the api changes).

It somehow breaks the dependency management idea that every package manages all of it's own dependencies. 

In my project I use plain java.util.logging, so I had no slf4j installed. The problem I had, is that due to that, pf4j was very silent and I was unable to detect bugs. 

The basic issue is that you can never know, which logging library a user might use. And not logging anything in case the user has not included slf4j is somewhat irritating.

However, I don't know how other libraries handle this issue..

**Comment by decebals** [comment]
I think that it's not a problem if you use other sl4j version in your `pom.xml`. 
If you don't have a slf4j implementation in your application then slf4j throws a gentle and informative message in console. So, based on that message you know that you must add a concrete slf4j implementation in your application.
I prefer to use a simple facade (abstraction) for various logging frameworks because for this 26KB (the size of slf4j-api) you offer a freedom to use their desired logging framework.
